---
title: "01_nutrients_and_chl"
author: "Julia Pop"
date: "2025-09-18"
output: html_document
---

```{r setup, include=FALSE}
# code to troublesheet file path issues. 
# By default, knitr uses the folder containing the .Rmd file as
# the working directory. This code allows us to set the folder
# with our .rProj in it as the root. 

# find_root looks upwards from the .Rmd until it finds a file or
# folder that matches the criteria "folder with a .Rproj file in
# it."

knitr::opts_knit$set(root.dir = rprojroot::find_root(rprojroot::is_rstudio_project))
```

# Chlorophyll calculations
```{r}
chl_df_combine %>%
filter(siteId %in% c("loc")) %>%  
mutate(dateSampled=ymd(dateSampled),       
	year=year(dateSampled)) %>%   
		ggplot(aes(x=dateSampled,y=chla_ugl,color=sampleLocation))+  
		 geom_point() +   facet_wrap(~siteId) +   
		geom_hline(yintercept=2.6) + #Oligotrophic cut off, Carlson 1977   
		geom_hline(yintercept=7.3)   #Mesotrophic cut off, Carlson 1977

```

# Nutrient calculations
```{r}




```