---
title: "02_GAMs"
author: "Julia Pop"
date: "2025-09-22"
output: html_document
---

```{r setup, include=FALSE}
# code to troublesheet file path issues. 
# By default, knitr uses the folder containing the .Rmd file as
# the working directory. This code allows us to set the folder
# with our .rProj in it as the root. 

# find_root looks upwards from the .Rmd until it finds a file or
# folder that matches the criteria "folder with a .Rproj file in
# it."

knitr::opts_knit$set(root.dir = rprojroot::find_root(rprojroot::is_rstudio_project))
```

#Libraries -- add these here
```{r}
# Bella's note-- usually I like to "source" a script that loads in all the R
#packages that I use in a particular project, that way each R markdown will
#run even if you didn't run all the previous R markdown files with the library()
#calls. 
source("scripts/libraries.R")
```

**NOTE! use the short files for the gams unless interested in comparing pigment units (g TC vs g dry mass)**

### Adding a weight term
```{r}

## Add weight to paleo data
### This is not very elegant but it does work
## You need to have a top row of blank cells to make this work - i.e, 0 depth and year of sampling
#### read in your data (now with dates!)
LFM_short <- read.csv("output/LFM_short.csv") 
### mutate your data
LFM_short <- LFM_short %>%
  mutate(interval = lag(year_CE) - year_CE) %>% ### use the interpolated dates to calculate temporal averaging
  slice(-1) %>% ## cut the top row of blank data
  mutate(weight = interval / mean(interval, na.rm=TRUE)) ### make the weight term 
  
### Now you have a weight term

```

### Gams - Cale's way
```{r}

m.beta <- gam(d15N ~s(year_CE, k = 10), # this is simply the trend by date
              data = paleo, ## the data used
              family=Gamma(link="log"), ## the family depends on the type of data. 
                  ## Use Gamma for concentration data
              bs='tp',## spline - thin plate is ok for simple models like this 
              method="REML", ## method - always use REML for gam
              weights = weight) ## here we add the weight term

# now check if the gam is good
summary(m.beta)
plot(m.beta)
gam.check(m.beta)
```

### GAMs- Bella's way
```{r}


```