---
title: "03_ancillary_data"
author: "Julia Pop"
date: "2025-09-24"
output: html_document
---

```{r setup, include=FALSE}
# code to troublesheet file path issues. 
# By default, knitr uses the folder containing the .Rmd file as
# the working directory. This code allows us to set the folder
# with our .rProj in it as the root. 

# find_root looks upwards from the .Rmd until it finds a file or
# folder that matches the criteria "folder with a .Rproj file in
# it."

knitr::opts_knit$set(root.dir = rprojroot::find_root(rprojroot::is_rstudio_project))
```

```{r}
source("scripts/libraries.R")

landcover <- read.csv("data/spatial data/annualNlcdStats_20250928.csv") %>%
  filter(Lake %in% c("FOURMILE_LAKE", # I assume this is Lower? Rename this
                       "UPPER_FOURMILE_LAKE",
                       "TURKEY_CREEK_LAKE")) %>%
  mutate(Lake = recode(Lake, "FOURMILE_LAKE" = "Lower Fourmile Lake"),
         Lake = recode(Lake, "UPPER_FOURMILE_LAKE" = "Upper Fourmile Lake"),
         Lake = recode(Lake, "TURKEY_CREEK_LAKE" = "Turkey Creek Lake"))

rg <- read.csv("data/spatial data/rockGlacierStatsDF_20250928.csv") %>%
  filter(Lake %in% c("FOURMILE_LAKE", # I assume this is Lower? Rename this
                       "UPPER_FOURMILE_LAKE",
                       "TURKEY_CREEK_LAKE")) %>%
  mutate(Lake = recode(Lake, "FOURMILE_LAKE" = "Lower Fourmile Lake"),
         Lake = recode(Lake, "UPPER_FOURMILE_LAKE" = "Upper Fourmile Lake"),
         Lake = recode(Lake, "TURKEY_CREEK_LAKE" = "Turkey Creek Lake"))
head(rg)

wsa <- read.csv("data/spatial data/watershedAreaDF_20250928.csv") %>%
  filter(lake %in% c("FOURMILE_LAKE", # I assume this is Lower? Rename this
                       "UPPER_FOURMILE_LAKE",
                       "TURKEY_CREEK_LAKE")) %>%
  mutate(lake = recode(lake, "FOURMILE_LAKE" = "Lower Fourmile Lake"),
         lake = recode(lake, "UPPER_FOURMILE_LAKE" = "Upper Fourmile Lake"),
         lake = recode(lake, "TURKEY_CREEK_LAKE" = "Turkey Creek Lake"))

#Run the full script to get some dataframes of SNOTEL data from Wolf Creek Pass
#and GRIDMET modeled data for climate from 1979-2024
source("analysis/pull_gridmet_snotel.R")
# (may take a few minutes to run on your computer)

#final SNOTEL dfs: snotel_data_combined (does not have calculated values, just raw) and snow_phenology_df (has calculated values)
#final dfs: gridmet_data (this one has no snow or calculated values); gridmet_data_snow (has snow estimated from precip and temp, and mean temp estimated from min/max); total_WY_snowfall (just estimated snowfall for each water year/site)


``` 

## Landcover

### Time series   
```{r}
landcover %>%
  filter(class_name %in% c("Evergreen Forest",
                           "Grassland/Herbaceous")) %>%
  ggplot(aes(x=year, y=percent_of_ws, color=Lake)) +
  geom_point(alpha=0.5)+
  facet_wrap(class_name~Lake, scales="free_y") +
  theme(legend.position="bottom")+
  labs(y="Landcover as\n% of watershed")+
  geom_smooth(method="gam", se=F, linetype="dashed")+
    scale_color_manual( breaks = c("Upper Fourmile Lake", "Lower Fourmile Lake", "Turkey Creek Lake"), 
    values = c( 
    "Upper Fourmile Lake" = "yellowgreen",  # 
    "Lower Fourmile Lake" = "#0072B2",  # 
    "Turkey Creek Lake" = "#D55E00"))
ggsave("figures/landcover/forest_shrubs_all_lakes.png",
       width = 8, height = 6, units = "in", dpi = 300)
```

###  Table of contemporary landcover
```{r}

landcover %>%
  filter(class_name %in% c("Evergreen Forest",
                           "Grassland/Herbaceous",
                           "Barren Land (Rock/Sand/Clay)",
                           "Emergent Herbaceous Wetlands",
                           "Woody Wetlands")) %>%
  filter(year=="2024") %>%
  select(Lake, class_name,percent_of_ws) %>%
  pivot_wider(names_from="class_name",
              values_from="percent_of_ws") %>%
  left_join(., wsa, by=c("Lake"="lake")) %>%
  arrange(desc(ws_area_km2)) %>%
  mutate(Wetlands = `Woody Wetlands` + `Emergent Herbaceous Wetlands`) %>% #combine categories
  select(-`Woody Wetlands`,
         -`Emergent Herbaceous Wetlands`)

```

## SNOTEL
### Plot time series

```{r}

# Graph SNOTEL data -------------------------------------------------------

head(snow_phenology_df)

# High interannual variability in maximum snow water equivelent
snow_phenology_df %>%
  ggplot(aes(y=max_swe, x=year))+
  geom_point()+
  geom_line()+
  labs(y="Annual max.
       snow water equivelent (cm)")+
  scale_y_continuous(limits=c(0,1500))


snow_phenology_df %>%
  mutate(
    # recalculate max_swe_doy for 1996.... 
    # something went wrong in the function above
    max_swe_doy = case_when(
      year == 1996 ~ yday(max_swe_date),
      TRUE ~ max_swe_doy
    ),
    # Convert DOY to a dummy date (e.g., year 2000)
    max_swe_date_dummy = as.Date(max_swe_doy - 1, origin = "2000-01-01")
  ) %>%
  ggplot(aes(x = year, y = max_swe_date_dummy)) +
  geom_point() +
  geom_line() +
  scale_y_date(
    date_labels = "%b %d",   # show month/day (e.g., Mar 15)
    date_breaks = "1 month",
    limits=c(as.Date("2000-03-01"),as.Date("2000-06-01"))
  ) +
  labs(
    y = "Date of Maximum SWE",
    x = "Year"
  ) 


snotel_data_combined %>%
  mutate(water_year = dataRetrieval::calcWaterYear(date)) %>%
  ggplot(aes(x=date, y=snow_water_equivalent)) +
  geom_point() +
  facet_wrap(.~water_year, scales="free_x") +
  geom_vline(xintercept=snow_phenology_df$max_swe_date) 

```

#### changepoint analysis?
```{r}
    # Install and load the package
    # install.packages("changepoint")
    library(changepoint)

    # Example: Detect change points in mean
    set.seed(123)
    data <- c(rnorm(50, 0, 1), rnorm(50, 5, 1))
    cpt_result <- cpt.mean(data, method = "AMOC")
    plot(cpt_result)
    
#max swe DOY
data <-  pluck(snow_phenology_df$max_swe_doy)
    
```
    
## GridMet
### Plot time series
```{r}

# Graph the gridmet data --------------------------------------------------
gridmet_data %>%
  mutate(year=year(date))%>%
  group_by(year) %>%
  summarize(pdsi=median(pdsi, na.rm=TRUE)) %>%
  ggplot(aes(x=year, y=pdsi))+
  geom_point()+
  geom_line()

gridmet_data %>%
  mutate(month=month(date),
         year=year(date))%>%
  group_by(month,year) %>%
  summarize(pdsi=median(pdsi, na.rm=TRUE)) %>%
  ggplot(aes(x=year, y=pdsi))+
  geom_point()+
  geom_line()+
  facet_wrap(~month)+
  labs(y="Mean monthly PDSI")+
  geom_smooth(method="gam")


total_WY_snowfall %>%
  ggplot(aes(x=water_year, y=total_snowfall))+
  geom_point()+
  geom_smooth(method="lm")


```

###Compare Gridmet snow with SNOTEL snow
More of a gut check, not needed for thesis.

```{r}
#How does this compare to estimates from SNOTEL?
head(snotel_data_combined)
total_WY_snowfall_SNOTEL <- snotel_data_combined %>%
  mutate(snowfall = case_when(
    temperature_mean < 0 ~ precipitation,
    temperature_mean >= 0 & temperature_mean <= 6 ~ pmax(0, precipitation - 0.1678 * temperature_mean), 
    temperature_mean > 6 ~ 0
  )) %>%
  mutate(water_year = dataRetrieval::calcWaterYear(date)) %>%
  group_by(water_year) %>%
  summarize(total_snowfall = sum(snowfall, na.rm = TRUE), .groups = "drop")

total_WY_snowfall_SNOTEL %>%
  filter(total_snowfall > 0) %>%
  ggplot(aes(x=water_year, y=total_snowfall))+
  geom_point()+
  geom_smooth(method="lm")

#Compare directly
full_join(total_WY_snowfall %>% rename(total_snowfall_gridmet=total_snowfall),
          total_WY_snowfall_SNOTEL %>% rename(total_snowfall_snotel=total_snowfall)) %>%
  filter(total_snowfall_snotel > 0) %>%
  ggplot(aes(x=total_snowfall_gridmet,
             y=total_snowfall_snotel)) +
  geom_point(aes(color=water_year))+
  geom_abline(slope=1,
              intercept=0)

```
## NADP 
